### ISSUE TITLE
Error messages need stacks

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#100]
The new error messages are pretty, but really hard to use.  This looks Pundle choked while trying to perform an HMR:

```
  Error   Cannot read property 'filePath' of undefined
```

but without a file name or line number, I don't even know where to begin debugging it.

**Comment by appsforartists** [comment]
Turns out it was this line:

```typescript
import '@types/chrome';
```

which to be fair, I also got another error about.  The `filePath` threw me off though.

**Comment by steelbrain** [comment]
Yeah I think that's a bug I recently fixed in master, it happens only when you add new files into bundle that weren't in before. Reloading page usualy fixes this, next release will fix it once and for all

**Comment by steelbrain** [comment]
Closing as it's fixed in master, but please do feel free to continue discussing
