### ISSUE TITLE
create-react-app like experience

### ISSUE THREAD

**Issue by nelix** [steelbrain/pundle#103]
Trying to think about things that would attract some attention, like demos and comparisons to webpack bundles.

A tool that improves the configuration situation for people, while still giving them the best result would also really help.

Are you interested in PR for stuff like this?

Are there any other marketing related resources out there already?

**Comment by steelbrain** [comment]
Hi @nelix 

I have not put a lot of effort into marketing Pundle as of yet, I'm saving it for the v2 release. I would however, appreciate all the help I can get for it :)
If you want a `create-react-app` like experience with Pundle, you should use it's CLI utility called [`motion`](https://github.com/motion/motion). It uses Pundle but provides a very simply lifecycle for doing most of the tasks
