### ISSUE TITLE
Can `debug` be set automatically?

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#104]
I'd like to have a single `.pundle` file for my project.  The only difference in configuration between dev and prod for most apps should be the `NODE_ENV` value.  Therefore, it would be great if this could be omitted from `.pundle` and inferred automatically:

If `--dev` is passed to the `pundle` bin, `debug:true`. 
If not, `debug:false`.

**Comment by steelbrain** [comment]
Thank you for the request @appsforartists as always 🎉 
As of https://github.com/motion/pundle/commit/2eb9a298e99c78a2427fd487bda3c65c06b9ecfa, if the user does **not** specify the `debug` prop in their config, we default it to true for dev server and false for anything else. Please note that the user can still override this behavior by setting the config themselves in the configuration file.

**Comment by appsforartists** [comment]
I dont think this is working.  Running `pundle` with `--dev` starts HMR, but `console.log(process.env.NODE_ENV)` returns `production`.

**Comment by steelbrain** [comment]
I'll investigate very soon

**Comment by steelbrain** [comment]
beta v12 fixes this. Thanks again for your continued trust in Pundle
