### ISSUE TITLE
Can't import JSX from TSX

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#106]
## Steps to reproduce ##

```
 git clone git@github.com:material-motion/material-motion-js.git
 cd material-motion-js/
 git checkout pundle-rename-reduction
 yarn run bootstrap
 cd packages/demos-react/
 yarn run start
```

- Navigate to http://localhost:8080/bottom-sheet/

- Rename `packages/demos-react/src/bottom-sheet/components/BottomSheetMain.tsx` to `packages/demos-react/src/bottom-sheet/components/BottomSheetMain.jsx`

## Expected Result ##

HMR notices the file change and tries to rerender (but the resulting HTML is the same).

## Actual Result ##

` Error   Cannot find module './bottom-sheet/components/BottomSheetMain' from 'src/routes.tsx'`

**Comment by appsforartists** [comment]
Incidentally, I'm also having a hard time getting Pundle to pick this up:

```javascript
// in midiconvert/package.json
  "jsnext:main": "src/MidiConvert.js",

// in .pundle
      require.resolve('pundle-preset-typescript'),
      {
        resolver: {
          packageMains: ['typescript:main', 'jsnext:main','browser', 'main'],
        },
        loader: {
          extensions: ['js', 'jsx', 'ts', 'tsx'],
        },
        transformer: {
          extensions: ['js', 'jsx', 'ts', 'tsx'],
          config: { compilerOptions },
        },
      },
```

If I put `packageMains` in `pundle-preset-default`, I get `unexpected keyword export` errors in Chrome, because Chrome doesn't yet support `import/export`, those would have to go through TS or Babel.

**Comment by steelbrain** [comment]
Yeah you have to basically set

```
presets: [
  ['pundle-preset-default', { loader: false }]
]
```
This disables the default loader-js that loads `jsx` and `js` extensions. You need it to redirect the load requests to the one in the typescript preset. This is for the second post.

I've fixed the main bug described in this issue in the first post in https://github.com/motion/pundle/commit/18e3d50918870181e0a0621a8caefe1bdaf882d7. I'm working on some fixes for windows and will publish a new beta after that. Reminder, your app still might need to rename some config props to `rootDirectory` like discussed previously to upgrade to the latest beta.
