### ISSUE TITLE
Make nice import names default

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#107]
Via this:

https://github.com/jamietre/babel-plugin-transform-es2015-modules-commonjs-simple

**Comment by steelbrain** [comment]
Pundle really has no default behavior. It has no default transformer, you have to manually add it. It has no default configuration of Babel, you have to add it. You have to specify everything manually, no defaults in this area.

Maybe this is better suited inside Motion. Let me know what you think

**Comment by natew** [comment]
Yea wasn't sure but we can move to motion, also looks like theres a tradeoff with this thing but its also no possible to integrate easily, so would be a cool config option in motion.

**Comment by steelbrain** [comment]
Closing this here as discussed
