### ISSUE TITLE
Make error more visible after finish

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#108]
Was banging my head over this for a bit. If there's an error during initial compile, it will finish and hang but look like it worked (if its not in screen):

Looks good:
![image](https://cloud.githubusercontent.com/assets/12100/21965460/1c9c5de8-db15-11e6-8f13-cc782df66163.png)

Scroll up:
![image](https://cloud.githubusercontent.com/assets/12100/21965462/219199da-db15-11e6-9aac-04a069343a9a.png)

Two potential solutions:

- Show message at end (Compile finished with 1 error + error again)
- Serve a custom error page to browser rather than their own index.html

**Comment by natew** [comment]
Also, I just fixed the path issue and refreshed, it doesn't seem like it picked it up! So repro:

- have error in import
- startup motion
- fix import
- still hangs

edit: turns out my npm watch hadn't picked up new folder... so in this case actually what would be helpful is showing whenever a new file compiles in motion even if its a node_module file (plus showing the "Compiled with 2 errors" would help so it would be more clear where it left off)

**Comment by steelbrain** [comment]
Working on a fix for this

**Comment by steelbrain** [comment]
I've pushed the recovering from error fixes in Pundle; it's in latest beta and showing a nice message on ready in motion as of https://github.com/motion/motion/commit/43744a75a5efda7808032c6e0bdcbc78c1875503
