### ISSUE TITLE
Regression: index.html no longer found in sourceRoot

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#113]
With this file structure:

```
- site/index.html
- site/dist/bundle.js
```

and this pundle config snippet:

```javascript
  output: {
    bundlePath: './site/dist/bundle.js',
    sourceMap: true,
    sourceMapPath: './site/dist/bundle.js.map',
  },
  server: {
    port: 8080,
    hmrPath: '/dist/bundle_hmr',
    bundlePath: '/dist/bundle.js',
    sourceRoot: path.join(__dirname, 'site'),
    sourceMapPath: '/dist/bundle.js.map',
    redirectNotFoundToIndex: true,
  },
```

`site/index.html` is found in beta2, but in beta9, it looks in `site/dist/index.html`, and serves ENOENT: file not found.

**Comment by steelbrain** [comment]
This is actually a configuration change between the versions. You need to specify `rootDirectory` in `output` configuration. I remember giving you a heads up about it

**Comment by steelbrain** [comment]
Also `server.sourceRoot` has been updated to `server.rootDirectory`. You can find out about the latest configuration by doing `pundle init full` in a temp directory and reading it's config. When released, pundle will have consistency and support guarantee but sorry can't provide it as I have to make a lot of changes in between
