### ISSUE TITLE
Pundle dev works, but build breaks with "Cannot set property '__esModule' of undefined"

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#114]
```
Uncaught TypeError: Cannot set property '__esModule' of undefined
```

Something about the way exports are being processed in beta11 breaks my builds - rolling back to beta2 fixes the problem (but only if I get rid of all the `^` dependencies - otherwise, I end up with a mess of some packages on one version and some on another).

**Comment by steelbrain** [comment]
It's presumably a bug in the wrapper, that I thought was fixed (and hell, was even fixed when I tested it). I'll investigate

**Comment by steelbrain** [comment]
PMed, couldn't repro the bug in b11, it was introduced in b10 and fixed in b11 (closing but feel free to continue discussing)
