### ISSUE TITLE
Consider removing `^` from version numbers

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#115]
Debugging a broken Pundle build is maddening, because the `^`s in the version numbers mean you end up with a mess of some old versions, and some new ones.  For instance, `pundle-dev@2.0.0-beta2` depends on `^2.0.0-beta2`, which resolves to `2.0.0-beta11`.  Even if I depend specifically on  `"pundle": "2.0.0-beta2"`, all my transitive dependencies end up on `beta11`.

Caret versions are used for deduplicating common dependencies, e.g. making sure you don't end up with 15 versions of `lodash` in your bundle because each dependency depends on a different patch version.  Since `pundle` is a dev tool, I'm having a hard time imagining a case where a dependency would itself depend on `pundle`.

Therefore, I recommend that you remove the `^`s from all the version numbers.  If an author wants to automatically get the latest version of `pundle`, they can use `^`s in their top-level `package.json`, but within a single pundle installation, all the modules should use the same version.

**Comment by appsforartists** [comment]
I probably spent an hour on what should have been a very simple rollback, because the caret versions kept implicitly upgrading me to a version I was explicitly trying to get off of:

http://codereview.cc/D2525

It was immensely frustrating.

**Comment by steelbrain** [comment]
It will be this way in beta13, I've removed all `^` from manifests

**Comment by steelbrain** [comment]
Released in v2b13
