### ISSUE TITLE
Three.js returns null from import

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#116]
Just tried it out with app, seems to not get anything on default import.

**Comment by steelbrain** [comment]
Unable to repro, you might actually be importing the incorrect library. The real three.js npm package is [`three`](https://www.npmjs.com/package/three) and requiring it returns correctly on v2beta12

<img width="914" alt="screen shot 2017-01-23 at 10 20 47 pm" src="https://cloud.githubusercontent.com/assets/4278113/22214663/4bd7d69a-e1ba-11e6-9bdf-f7e4188df8cc.png">

**Comment by natew** [comment]
Yea it was three. I had to destructure everything the default was null
