### ISSUE TITLE
Flow error for local installation

### ISSUE THREAD

**Issue by codemonkey800** [steelbrain/pundle#118]
I prefer installing dependencies locally rather than globally. Running flow after installing pundle results in the following error:

```sh
node_modules/pundle-api/types.js:6
  6: export type { FileIssue, MessageIssue } from './src/issues'
                                                  ^^^^^^^^^^^^^^ ./src/issues. Required module not found


Found 1 error
```
Here's my flowconfig:

```ini
[ignore]
<PROJECT_ROOT>/.venv/.*

.*/node_modules/fbjs/lib/.*
.*/node_modules/jss/.*
.*/node_modules/pundle-api/spec/.*
.*/node_modules/react-swipeable-views/.*

[libs]
flow-typed

[options]
```

I get this error because the src directory in the [pundle-api](https://github.com/motion/pundle/tree/master/packages/api) package is ignored by npm.

Another option could be to add pundle to [flow-typed](https://github.com/flowtype/flow-typed).

**Comment by steelbrain** [comment]
Fixed as of https://github.com/motion/pundle/pull/101/commits/d7fdb527b2397b7fadc95a0ebacda7a9a0f8d212 will be part of v2b13
