### ISSUE TITLE
Implement global Buffer variable

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/pundle#131]
Currently it only works for those who import it

**Comment by steelbrain** [comment]
Current workaround is to have `global.Buffer = require('buffer')` in entry point

**Comment by natew** [comment]
related, i've had to shim process.nextTick and other process things a few times. Not sure best practice here but would be worth investigating into what webpack/browserify do.

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/pundle/commit/038012da8e63602c62c1bfd91d2062ca787648be and https://github.com/steelbrain/pundle/commit/27e99126d50ffcf6ae818eb446b02deb202dcad8
