### ISSUE TITLE
Installing instructions incomplete

### ISSUE THREAD

**Issue by dany-on-demand** [steelbrain/pundle#132]
`npm install -g pundle@latest` is not enough, there are some deprecation warnings too

I installed `pundle-cli` but it was still missing dependencies

do you need to install from git? or just clone the project and avoid npm?

**Comment by steelbrain** [comment]
Hi @dany-on-demand

The installation docs are a little incomplete, and I'm working on that. but while I do that, here's how you can try the latest pundle (through our create-react-app like cli, [`motion`](github.com/motion/motion)).

```
npm install -g motion@5.0.0-beta18

cd ~
motion new my-new-app
cd my-new-app
motion
# use "help' command inside motion console for a list of commands
```
