### ISSUE TITLE
HMR docs

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#134]
Spent 30m reading through and playing with hmr stuff in pundle (searching code here and in macro app).

I got the updated pundle working nicely with our new stack, and want to make the nice HMR plugin that accepts individual views and reloads them (and redo do it a bit more like react-hmr).

I'm confused as I don't see anywhere where we were doing a `module.hot.accept` in macro, even in store-hmr transform or the view.provide decorator. I know that pundle-generator has different accept behavior than typical, and if I add a `module.hot.accept()` to any file it seems to prevent the tree from propagating further. Beyond that, I imagine we'd have needed to proxy components and hit forceReload on them once they are accepted, and don't see where we were doing that.

I guess my ideal would be a transform that can recognize view-components (my best bet on doing this would be: find exports, see if exports are either: function that returns JSX or class with render that returns JSX). If all exports are views: accept them and trigger their proxy reload after accept.

Mostly want to be sure I understand how accept works in pundle vs webpack, and if we had some code I'm missing that did this.

Willing to put a bit of work and add documentation once I get it working.

**Comment by steelbrain** [comment]
> if I add a module.hot.accept() to any file it seems to prevent the tree from propagating further

This is defined by the [HMR specification](https://webpack.github.io/docs/hot-module-replacement.html). Pundle and Webpack have the same API. You could look into [`react-transform-hmr`](https://github.com/gaearon/react-transform-hmr) and see how it propogates the error above because it works flawlessly in Pundle as well.

**Comment by natew** [comment]
Good to know it follows spec!

Was confused [when I read this](https://github.com/steelbrain/pundle/tree/6f70c6c99772b82ed039b5c4ab7e96f50b768918/packages/generator-default).

**Comment by natew** [comment]
Seems to be working well!
