### ISSUE TITLE
HMR failed, handshake response code: 200

### ISSUE THREAD

**Issue by ncammarata** [steelbrain/pundle#135]
```WebSocket connection to 'ws://jot.dev/_/bundle_hmr' failed: Error during WebSocket handshake: Unexpected response code: 200```

When I run an app for the first time, this error shows in the console and HMR doesn't work. Let me know if I can be more specific!

**Comment by steelbrain** [comment]
Is `jot.dev` the correct address and are you using HTTPs by any chance?

**Comment by ncammarata** [comment]
jot.dev is correct and I am not using https

**Comment by natew** [comment]
We havent seen this in quite a while, think it's ok to close.
