### ISSUE TITLE
Cannot find module react-dom on project creation

### ISSUE THREAD

**Issue by ncammarata** [steelbrain/pundle#136]
![image](https://cloud.githubusercontent.com/assets/204989/26387284/2aeed974-4001-11e7-895c-b9f6ca4250a3.png)

I get this error on initial creation of an app.

**Comment by steelbrain** [comment]
NPM Installer fails on master, you should install the dependencies manually until its fixed in the newer version

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/pundle/commit/6de67bdcfaae2b5ee4bcbb7da16c1d8199f9834d
