### ISSUE TITLE
Invalid imports don't throw errors while running or recover once fixed

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#137]
This one took me a little while today. Not sure if it was due to some other thing happening because replicating isn't consistent but:

1. Import missing file
2. Fix import

**Comment by natew** [comment]
Also if invalid import on startup it won't finish, I'm sure related to same bug.

**Comment by steelbrain** [comment]
Working on a solution for this

**Comment by natew** [comment]
Fixed on master
