### ISSUE TITLE
[HMR] Hook to listen for HMR event in browser

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#141]
Looking for this because we have runtime error catching using `unstable_handleError` in React now, and show a redbox. I'd like to clear the redbox when an hmr comes in. But we are using react-hmr-transform, which controls that whole process.

Something like `__sbPundle.on('hmr')` would be nice.

**Comment by steelbrain** [comment]
You can do `localStorage.setItem('__sbPundleDebugHMR', 'true')` to enable debug logging of HMRs if that's helpful.

What's the possible usecase of hooking into HMR btw? ICYMI you can do `module.hot.accept` twice in the same file, so both your code and `react-hmr-transform` can get the events

**Comment by natew** [comment]
I guess problem is this:

1. Error happens in sub-tree, propagates up to root which catches in unstable_handleError and calls setState to show an error.
2. Now you save a sub-tree file with a fix
3. That doesn't propagate up because HMR patches just that file.

So I'd need to write some sort of module.hot.accept into every view, and have the hmr transform check for errors and clear them there. Which is doable, but seems a bit cumbersome.
