### ISSUE TITLE
A bit aggressive with watching changes

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#142]
When you re-compile a sub-module or directory that pundle is watching, things go a bit haywire as it attempts to re-run after every file change.

A tiny debounce would be helpful here. Maybe 40ms.

Perhaps this is only an issue because imports fail currently, which causes rebuilds to always break motion.

**Comment by steelbrain** [comment]
Sounds fair

**Comment by steelbrain** [comment]
We currently have a "cooldown" of 60ms on all changes. Will investigate this further and see if we need to increase it for big repositories or have a back-off logic

**Comment by steelbrain** [comment]
No longer an issue, can survive entire codebase delete / recreate without any issue
