### ISSUE TITLE
No file or directory _empty.js inside readable-stream

### ISSUE THREAD

**Issue by ncammarata** [steelbrain/pundle#145]
![image](https://user-images.githubusercontent.com/204989/27302684-f1400bca-54ec-11e7-9399-22f1c753ebac.png)

I get this after installing latest motion globally. If I `touch` that file, it works.

**Comment by steelbrain** [comment]
Can I have the steps to repro this issue?

**Comment by ncammarata** [comment]
I've tried to repro and can't. I'll open again if I see it again and can repro
