### ISSUE TITLE
Announcement for 2.0

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#146]
We should do this properly!

I would propose:

- [ ] Have a simple splash site with docs and pundle branding
- [ ] Have an announcement blog post on the site that speaks to Pundle's philosophy
- [ ] Have a series of tweets we send out
- [ ] Finish docs on the repo enough that people can get started easily

I started working on what can become a simple summary of what Pundle is/wants to be. This could be condensed into tweets, or expanded into a blog post. Feel free to help me refine it further.

## Pundle announcement
Pundle (a next gen JS bundler) is nearing it’s big 2.0 release 🎉. How does it stack up to webpack?

- Focus on getting plugin/internal API's to be powerful and consistent
- Cached boot
- Faster incremental compile
- Built in light CLI to run apps with HMR out of the box
- Improved plugins, easier to write & compose (inspired by Babel)
- Flow-typed from the start

What features does it support?

- Loaders (has js, json, url, ts for now)
- Dedupe
- Code splitting with import()
- NPM install plugin
- Commons Chunking
- Uglify, Typescript, …

**Comment by natew** [comment]
By the way, things have been working relatively well. I get bugs sometimes where it stops updating a file and serves an old version, you have to restart without cache to fix. Confusing certainly, I'll try and post any errors I run but usually it's no error just old files.

Also, just ran across [fuse-box](https://github.com/fuse-box/fuse-box) looks interesting. We could do with a readme exactly like theirs.

**Comment by steelbrain** [comment]
I was brainstorming a few hours ago and have changes in mind that will speed up Pundle upto 2x, v2 will take some time

**Comment by natew** [comment]
I agree, though I've been getting lots of people interested in trying it!

Perhaps a beta release where we just have docs that are a bit better for users not just developers would be worth doing. I really want to take a stab at the docs but am desperately working on about 10 other things. I'd even sponsor with $ for someone to do it! Pundle Patreon?

**Comment by natew** [comment]
Also final thing, we should remove `motion` and just use `pundle` as the CLI. I think it would make things way more clear for everyone.

**Comment by steelbrain** [comment]
I personally like both seperately kinda like webpack + create-react-app, motion is create-react-app and pundle is webpack but I could see how that would be confusing

Current Pundle is pretty stable with what it has, just minor bug about resuming from cache with multiple chunks, I think you're right. We should cut out a release with docs and that bug fixed and then work on the big changes
