### ISSUE TITLE
[bug] deep-extend duplicate arguments

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#147]
Getting this when requiring 'gloss':

bundle.154.js:37652 Uncaught SyntaxError: Duplicate parameter name not allowed in this context

![image](https://user-images.githubusercontent.com/12100/27306057-10577bcc-54f9-11e7-9780-2080928305d1.png)

**Comment by natew** [comment]
Tried adding `injections.unique.has('buffer')` without luck so far...

**Comment by natew** [comment]
Ok have a fix for this, unique did work just needed to disable cache. Now:

Uncaught TypeError: Buffer is not a constructor

![image](https://user-images.githubusercontent.com/12100/27306283-ec85a07e-54f9-11e7-8ae9-163eae2c5c84.png)

**Comment by steelbrain** [comment]
Will fix later today, bug is that it does `Buffer = require('buffer')` instead of `Buffer = require('buffer').Buffer`

**Comment by steelbrain** [comment]
Fixed in beta26
