### ISSUE TITLE
Regression: picking up parent .babelrc

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#148]
This ties into weird processing of babelrc in general, but seems like new versions are picking up config from a parent dir .babelrc suddenly.

Setup is: .motion.json with config, parent dir with .babelrc.

Expected: just use motion.json
Happened: used .babelrc

**Comment by steelbrain** [comment]
You can just create an empty babelrc in project root, left this enabled on purpose because it's the default behavior of any other babel consumer development tool

**Comment by natew** [comment]
What seemed to be happening was some sort of merge of the two, which I thought was weird.
