### ISSUE TITLE
empty file in readable-stream

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#149]
24006c7fa35f5116c23d485a29db3006a6e66a06

![image](https://user-images.githubusercontent.com/12100/27366486-48cfaddc-55fb-11e7-84c4-1ad3e6fc65a8.png)

**Comment by steelbrain** [comment]
Steps to repro would help me fix

**Comment by natew** [comment]
For me it's on a fresh install, first time I create a motion app. Sorry for not writing anything, we talked about this in earlier ticket but I thought it went away.

**Comment by natew** [comment]
a `touch` on that file usually works in fixing this.

**Comment by natew** [comment]
Got it again on a new install:

![image](https://user-images.githubusercontent.com/12100/27664017-27701076-5c1a-11e7-8503-0bdab1bc0241.png)

**Comment by steelbrain** [comment]
Confirmed fix in master
