### ISSUE TITLE
global deprecated error

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#151]
Attempting to debug this but stack traces are so weird.

Getting:

```DeprecationWarning: 'root' is deprecated, use 'global'```

![image](https://user-images.githubusercontent.com/12100/27511240-a269243c-58d4-11e7-9fda-a2a24fb6b0a0.png)

![image](https://user-images.githubusercontent.com/12100/27511231-9354e922-58d4-11e7-9fb0-395ac4e1838d.png)

Seems to be coming from an emitter inside process, which I assume is polyfilled by pundle.

**Comment by natew** [comment]
Unfortunately it doesn't give me much more than that.

![image](https://user-images.githubusercontent.com/12100/27511255-c3ab16aa-58d4-11e7-8852-b6ec8cd63b2c.png)

**Comment by steelbrain** [comment]
Fixed in master
