### ISSUE TITLE
Error babel-preset-steelbrain not found when not using babel-preset-steelbrain

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#152]
Steps to repro:

1. Install
2. Create app
3. Change preset to babel-preset-env
4. Run app, fails.

**Comment by steelbrain** [comment]
NPM Installer doesn't install plugin dependencies, if you do a `motion new` on latest version you'll see it asks you to do an npm install, so do that :)

**Comment by natew** [comment]
This was separate from that, we installed a different preset and were using that happily with older motion, but latest master it for some reason got confused about it and tried to access the steelbrain preset inside our app, despite no reference to it anywhere.

**Comment by steelbrain** [comment]
This is no longer an issue since Pundle no longer ships a babel preset of it's own and advises use of `@babel/preset-env`, `@babel/preset-react` among others
