### ISSUE TITLE
Support import statements

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#154]
Just tested this and it seems to fail (setting modules: false in babel-preset-env)

**Comment by steelbrain** [comment]
You shouldn't be setting modules to false in env preset. We'll have native support for imports when support for tree shaking lands until then use babel

**Comment by natew** [comment]
Ok just was trying because react-hot-loader expects it to be false to work and I'm attempting to get hmr right finally, (see https://github.com/gaearon/react-hot-loader/issues/565). We are close but a few bugs in that repo are holding back so am just exploring.
