### ISSUE TITLE
Changing from preset-steelbrain fails on start

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#158]
Steps to repro:

1. motion new
2. Change preset-steelbrain to another preset
3. Start app (after install is fine too)

Should throw an error about trying to resolve preset-steelbrain.

**Comment by natew** [comment]
Be sure to remove preset-steelbrain from the local app node_module.s

**Comment by steelbrain** [comment]
Can confirm, fixing

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/pundle/commit/539b471fabd300a2234afe0fddc8fb3c914f1669
