### ISSUE TITLE
Rename motion to pundle, use just Pundle cli

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#159]
This will be way clearer to everyone but us, and should make it much easier to explain and document for beta.

**Comment by appsforartists** [comment]
What about `create-pundle-react-app`?  Then, it could be used by [`yarn create`](https://yarnpkg.com/blog/2017/05/12/introducing-yarn/)

**Comment by steelbrain** [comment]
@appsforartists That's an excellent idea! Will also allow people to have project-specific pundle versions by default. Going with that

**Comment by steelbrain** [comment]
Done!

Pending on a release but the change itself is done
