### ISSUE TITLE
Having pouchdb-adapter-memory in package.json breaks app, even if not required

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#165]
Basically as title says, if I install `pouchdb-adapter-memory` but don't require it anywhere, I still get this error on startup:

```
Cannot find module 'leveldown/package.json' at node_modules/@mcro/models/node_modules/levelup/lib/leveldown.js
```

**Comment by natew** [comment]
Very minor for me, but seems like a legit bug in pundle checking for package.json's.

**Comment by steelbrain** [comment]
Are you sure you did not have a local NPM cache issue? because I don't think you can publish to the npm registry without a package.json.

I'd recommend clearing npm cache, removing node modules and reinstalling as error exists outside of pundle

**Comment by natew** [comment]
Pundle actually throws the error even though I never require that module
directly, it just was inside my node_modules. I'll try and repro on a clean
repo.
