### ISSUE TITLE
Be able to pass options to pundle from .motion.json

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#167]
I was trying to do something like this:

![image](https://user-images.githubusercontent.com/12100/31310973-4b70896a-ab57-11e7-8e2f-6b24c2aa673f.png)

Because we want to grab a specific packageMain in our env. Secondly, actually, we want to do this differently depending on production/development.

So a second consideration is can motion have different config for builds or for env?

**Comment by steelbrain** [comment]
Current config allows this and much greater control too
