### ISSUE TITLE
Weird one, ?react_perf loads both production and development react

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#170]
A quick google didn't show anyone else having this issue so my guess is this may be some fuzzing React does that fails with pundle.

Basically: Load a pundle react app in electron with ?react_perf and it will attempt to load react.production.js and react-dom.production.js when dev is already loaded.

Filing here first. Going to do a search for react_perf in the React repo and see where it tries to load production.

**Comment by steelbrain** [comment]
Fixed in master, dead if/else nodes are removed and only the ones remaining aka either prod or dev (but never both) are included in output
