### ISSUE TITLE
Pundle breaks on pouchdb-adapter-memory

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#171]
Hey, haven't run into an issue on correctness in a while but just got caught on this one.

Minimal test case would be to do this in a new pundle app:

```
import RxDB from 'rxdb'
```

And import the latest `7.1.0` rxdb package.

It seems to try and import the node levelup package from within pouchdb-memory-adapter. Unfortunately it's easy to get lost trying to follow the dep chain there, I got a ways down but didn't see any browser fields.

**Comment by natew** [comment]
Parent issue: https://github.com/pubkey/rxdb/issues/376

**Comment by steelbrain** [comment]
Sounds like a bug in the browser package resolver, should be fixed in the rewrite already

**Comment by natew** [comment]
Ah ok, is ng at a testable point? I can give it a run tonight or tomorrow.

**Comment by steelbrain** [comment]
It does not have a dev server yet but the build pipeline is complete.
Here's how you can test it

```
$ git clone https://github.com/steelbrain/pundle
$ cd pundle
$ yarn
$ cd packages/example
$ node lib
```
and then the dist files will be in `packages/example/public`

**Comment by steelbrain** [comment]
Fixed in master
