### ISSUE TITLE
Simple readme for running apps

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#174]
May have time this weekend to play with pundle 🙌 

Any tips for running an app?

Also, plans to make it work like parcel (index.html entry point)?

**Comment by steelbrain** [comment]
There are no plans to support no-config experiences as people have no sane way to configure them and are left more confused than satisfied.

I do have plans to support a `create-pundle-app` experience tho that will set everything up for you so you can just fill in the entries and have it working.

The current best README is the `test-package` in this repository, https://github.com/steelbrain/pundle/tree/rewrite-ng/packages/test-package

With that said, I'll be working on more docs soon

**Comment by natew** [comment]
Sounds good. I had a good time with parcel personally. But just docs on how
to run a standard app would be great.

**Comment by steelbrain** [comment]
FYI, `create-pundle-app` and `create-pundle-react-app` are now published.

If you have yarn you can do `yarn create pundle-react-app myapp` and follow instructions on screen
