### ISSUE TITLE
Unexpected token / How to clear cache?

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#179]
Getting close to having it working :party_parrot:!

Getting this now:

![image](https://user-images.githubusercontent.com/12100/42921374-98b78db4-8ad0-11e8-80c9-1d26e58bc4d4.png)

I'm trying to use `@mcro/babel-preset-motion` (published).

I tried this config:

```
module.exports = {
  presets: [
    '@mcro/babel-preset-motion',
    ['@babel/preset-env', { targets: { node: '7.0' } }],
  ],
}
```

But the preset doesn't seem to apply. Then I linked in `@mcro/babel-preset-motion` locally and commented out the react hot loader line. Seemed to not change that file from having the react hot loader wrapper.

This also didn't seem to pick up:

```
module.exports = {
  presets: [
    ['@mcro/babel-preset-motion', { disable: 'react-hot-loader/babel' },
    ['@babel/preset-env', { targets: { node: '7.0' } }],
  ],
}
```

Which should have disabled it. Trying a new app now to see if it's some cache thing.

**Comment by natew** [comment]
Cool yea verified it was some caching, a new app didn't have the problem!

**Comment by steelbrain** [comment]
For future reference, you can do `--cache.reset` to reset the cache.

You can also do `--help` and see a list of options supported by pundle!
