### ISSUE TITLE
No update on changing linked modules outside project root

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#180]
Using a mono-repo and editing some sub-deps it seems not to trigger pundle updates until i restart the server itself.

I looked into preset-default and `--help` for some config options and didn't see anything clear for this specific case.

**Comment by steelbrain** [comment]
Pundle by default only watches the root directory. This will be changed to eventually all the required files regardless of where they are but It's gonna take time

**Comment by steelbrain** [comment]
While watcher support for individual files is some time away, I've set `followSymlinks` to `true` in chokidar (`nsfw` watcher doesn't support it). So when https://github.com/steelbrain/pundle/commit/f9b5489bf19c26b585097da05308c5b2f866811b is released, you should be able to do `--watch.adapter chokidar` to fix watcher support for linked modules outside root directory

**Comment by steelbrain** [comment]
Update! The change was released. You can append `--watch.adapter chokidar` to your dev command to fix watching linked directories

**Comment by natew** [comment]
Guessing this is no longer issue because chokidar was removed?

**Comment by steelbrain** [comment]
`nsfw` was removed and chokidar was made default, so yes, this shouldn't be an issue in latest release
