### ISSUE TITLE
Typeorm / Module alias or exclude

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#182]
We have shared models between a client side and server app using typeorm.

Typeorm has a way to require `typeorm/browser` but when you do so in Pundle it causes this error (once your load the page):

```
Error: Cannot find module 'react-native-sqlite-storage' from '/Users/nw/github/my-app/node_modules/typeorm/browser/driver/react-native'
    at /Users/nw/github/my-app/node_modules/resolve/lib/async.js:46:17
    at process (/Users/nw/github/my-app/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/nw/github/my-app/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/nw/github/my-app/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/nw/github/my-app/node_modules/resolve/lib/async.js:92:31)
    at /Users/nw/github/my-app/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:170:21)
```

In webpack it shows a warning, but doesn't error. I believe the typeorm creator is working on fixing this on his side: https://github.com/typeorm/typeorm/issues/2158

Is there some way we can patch this pundle-side until then? Just ignoring the import would work I believe.

**Comment by steelbrain** [comment]
Oh this is interesting. Working on a fix

![image](https://user-images.githubusercontent.com/4278113/43121254-90d7395e-8f36-11e8-9923-201daca64adc.png)

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/pundle/commit/bbe7aa8207e7007b0fa0fc8d7cbf2dc664b566bf
