### ISSUE TITLE
Import order error

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#185]
beta6, importing this: `gatsby-remark-emoji`

![image](https://user-images.githubusercontent.com/12100/44608770-dcc4d980-a7a9-11e8-89e0-2eaca9cf716a.png)

**Comment by steelbrain** [comment]
Try restarting, make sure you hit it still

**Comment by natew** [comment]
I restarted, I'll try clearing cache

**Comment by natew** [comment]
Still get with cache clear

**Comment by natew** [comment]
I can remove this one for now.

**Comment by natew** [comment]
Sorry to spam. Added you on discord. Trying to set up pundle with stack but running into things so maybe less noisy to debug there.

**Comment by steelbrain** [comment]
Fixed in beta v7.
For the record the dependency had a template string literal instead of string literal
