### ISSUE TITLE
Using npm package `electron`

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#36]
`[Error: Unable to resolve './lib-cov/electron' from '$root/node_modules/electron' at /Users/nw/motion/packages/motion/node_modules/pundle/lib/path.js:59:15]`

**Comment by steelbrain** [comment]
Why would you want to use a node.js command line interface package in pundle?

**Comment by natew** [comment]
Ah I totally misread that package late last night. Thought it would let me control electron from browser.
