### ISSUE TITLE
Babel plugin doesn't run with dev-server.

### ISSUE THREAD

**Issue by eldh** [steelbrain/pundle#52]
I can't get the babel plugin to run with the dev-server. It seems to load fine, but the code is never transpiled. I'm assuming it's a config error? I've tried looking through the source code but I don't quite understand where the plugins are supposed to be applied. 

My config is here: https://github.com/eldh/jour/blob/master/dev-server.js. And I guess cloning that repo and doing `npm i && npm start` would reproduce the issue.

**Comment by steelbrain** [comment]
Investigating

**Comment by steelbrain** [comment]
Fixed in pundle@1.0.1 and pundle-dev@1.0.1

**Comment by steelbrain** [comment]
On a side note you might want to execute `loadPlugins` and `activate` in a series like

``` js
server.pundle.loadPlugins([
  [require.resolve('babel-pundle'), babelConfig],
]).then(function() {
  return server.activate()
}).catch((e) => console.log('error', e))
```

**Comment by eldh** [comment]
Awesome, thanks a lot! Great work on Pundle!
