### ISSUE TITLE
Create pundle-errors package

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/pundle#59]
All plugins and loaders will throw `PundleError` then and we'd know if we should show just the error message or a stack trace based on that

**Comment by amio** [comment]
Any specific idea of the log UI? I've seen an [amazing one](https://twitter.com/andreypopp/status/758251557100064768) recently:

![coxzsg6wgaayfpz](https://cloud.githubusercontent.com/assets/215282/17257930/0ee38fa8-55f7-11e6-972f-588a0b98ea55.jpg)

**Comment by steelbrain** [comment]
@amio That looks amazing, I'll definitely try to get something like that working with Pundle :)

**Comment by steelbrain** [comment]
Fixed in Pundle [v2Alpha1](https://github.com/motion/pundle/releases/tag/v2.0.0-alpha1)
