### ISSUE TITLE
Allow the use of a pundle config file.

### ISSUE THREAD

**Issue by AriaFallah** [steelbrain/pundle#63]
Right now, although powerful, having to manually go through the boilerplate steps of calling `pundle.compile`, `pundle.generate`, and `fs.writeFileSync` all in different promise blocks is a hassle. I know it's not that big of a deal, but I feel like since every other alternative offers a config file, the programmatic approach can scare newcomers away.

`pundle-dev` kinda solves this problem with it's `server` config, but that doesn't work with just pundle by itself.

It'd be nice to have something like:

``` js
export default {
  entry: ['index.js'],
  rootDirectory: './src',
  pathType: 'filePath',
  moduleDirectories: ['node_modules'],
  plugins: [
    ['babel-pundle', { config: { presets: ['steelbrain'] } }],
    'pundle-some-magical-plugin'
  ],
  loaders: [
    { extensions: ['.coffee'], loader: 'pundle-coffee' },
    { extensions: ['.less'], loader: 'pundle-less' }
  ],
  sourceMap: true,
  outputDirectory: 'lib'
}
```

The API for the config file would probably be different than this, but you get the idea. You could also add a `server` block if you instead to use this config with a server. It also carries the benefit of being more readable.

**Comment by steelbrain** [comment]
I love the idea!

**Comment by steelbrain** [comment]
This has been implemented in https://github.com/motion/pundle/pull/75
I'll keep this open until it's merged

**Comment by steelbrain** [comment]
Fixed in Pundle [v2Alpha1](https://github.com/motion/pundle/releases/tag/v2.0.0-alpha1)
