### ISSUE TITLE
Separate the concept of a plugin from the concept of a file transformation.

### ISSUE THREAD

**Issue by AriaFallah** [steelbrain/pundle#64]
### Why

As per my comment here https://github.com/motion/pundle/issues/62#issuecomment-236336001,  I think the separate concepts of a plugin and a transform are conflated, and pundle can benefit by making the concepts distinct.
- It would make pundle easier to understand in my opinion since it'd map 1-to-1 with the concept of [Extract-Tranform-Load](https://en.wikipedia.org/wiki/Extract,_transform,_load).
  - Extract = `require()`
  - Transform = transforms/transformer <- new addition to replace `plugin`
  - Load = loaders
- This frees up the word plugin to mean `side-effects` of the ETL process.
  - An eslint plugin to log errors
  - A plugin to install npm packages if they're found in the code.
  - Anything else someone wants to do by hooking into pundle
- In my experience / in my opinion, separating impure/pure code makes it easier to maintain pundle, and it would make it easier for users to see where their problems are occurring.
### How

Add a new `loadTransformers()` function that puts each of the transformers into an array called `this.transformers` or something like that. The after the line [here](https://github.com/motion/pundle/blob/43df14e2e8e36cce409b14c70b49deacf25386a9/packages/pundle/src/index.js#L76) where you emit the before-process event do something like

``` js
let result = event.contents
for (const transformer of this.transformers) {
  result = transformer(this, filePath, result, event.sourceMap)
}
result = loader(this, filePath, event.contents, event.sourceMap)
```

Thoughts?

**Comment by steelbrain** [comment]
I'm in favor of separating plugins and transformers. We would ideally have just one `.load()` that accepts both Plugins and Transformers.

It should be done with the change mentioned in https://github.com/motion/pundle/issues/61#issuecomment-236334324

I'll post an update after I figure out a realistic API or the flaws in the one discussed

**Comment by steelbrain** [comment]
Fixed in Pundle [v2Alpha1](https://github.com/motion/pundle/releases/tag/v2.0.0-alpha1)
