### ISSUE TITLE
Modules run in strict mode?

### ISSUE THREAD

**Issue by eldh** [steelbrain/pundle#68]
I updated pundle-dev from 1.0.1 to 1.1.4 and got errors that seems to be caused by modules running in strict mode (basically this: http://stackoverflow.com/questions/31221357/webpack-firebase-disable-parsing-of-firebase). Is this a bug or something that can be fixed with config?

**Comment by steelbrain** [comment]
Investigating

**Comment by steelbrain** [comment]
Fixed in Pundle v1.1.5
We were accidentally adding `"use strict";` to wrappers (Babel, duh)

**Comment by eldh** [comment]
Awesome, thanks for the quick fix.
