### ISSUE TITLE
Implement static content loader

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#71]
Not sure how great an idea this is, but a string loader at least would help me with a couple things. Specifically, we are using svg's and I want to share between a few different apps by putting in a package. So, naturally this would help.

For now the process is manual: copy and paste into a string inside a js file.

**Comment by steelbrain** [comment]
We already have support for custom loaders, we just have to write a loader for svgs or any static content

**Comment by steelbrain** [comment]
Static content loader (as well as transformer so you have files <2kb in size etc as data-urls instead of paths) is done in master
