### ISSUE TITLE
"Sending HMR 0" if `--hmr` not sent

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#78]
It's easy for a new user to think that HMR is on, even if they forgot the `--hmr` flag, because the logs still mention it

```
Pundle:Server Sending HMR of 0 file(s) to 0 connection(s) +43s
Pundle:Watcher File Changed :: ~/pundle/packages/test/src/index.js +21s
```

Should HMR ever be off in the Dev Server?  It should probably default to on.  If it is off, `HMR disabled` is a better message than `Sending HMR 0 file(s)`.

**Comment by steelbrain** [comment]
Sounds fair

**Comment by steelbrain** [comment]
Fixed in Pundle [v2Alpha1](https://github.com/motion/pundle/releases/tag/v2.0.0-alpha1)
