### ISSUE TITLE
devServer onboarding experience needs love

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#79]
```
../devServer.js --entry --hmr ./index.js
```

In the browser console, when I hit save:

```
bundle.js:1 Uncaught Error: Unable to apply HMR because some modules didnt accept it
```

How do I accept HMR modules?  Why doesn't the dev server do this by default?

**Comment by steelbrain** [comment]
Pundle is actually a low-level library, to see an example or actually use it in a project, try this

```
cd /tmp
npm install -g motion@latest
motion new app
cd app
motion
```

then in the motion terminal write `open` and press enter.
You'll see a working react app with HMR, then you can edit the app with an editor of your choice and explore how HMR is accepted etc

**Comment by appsforartists** [comment]
It looks like I can just put this at the end of the index file:

```
if (process.env.NODE_ENV === 'development' && module.hot) {
  module.hot.accept()
}
```

That makes pundle think the HMR is accepted, but it doesn't appear that the package is being reevaluated, or that `accept` takes a callback.  (I tried adding `console.log`s all over the place, but couldn't get any of them to trigger on HMR.)

I know @natew is always talking about how he thinks people should try `pundle` as a webpack replacement, so I'd expect better documentation on how to use it's magic-super-fast HMR.  That's the whole reason I'm considering using it as my dev server.  😃

**Comment by steelbrain** [comment]
I'll setup an example HMR app and put it on gist.github.com soon.

**Comment by appsforartists** [comment]
Thanks!

**Comment by steelbrain** [comment]
Man, so sorry for the trouble, just found out that we had a little typo introduced last week that broke HMR (but strangely enough, didn't break our app). I've fixed it in the latest release.

Also here's an [example setup](https://gist.github.com/steelbrain/a3799295a3a4c52543d35ab002553df9)

**Comment by appsforartists** [comment]
Thanks!  I tried that setup with TypeScript, and it HMRs instantaneously. 😀 

Can you please publish `pundle-typescript` to NPM?

``` typescript
// something.ts

// NOTE: Change this value and look at dev console to see HMR in effect
const dog = 'Doge?...'
export default dog;

//index.ts

import something from './something';

if (module.hot) {
  module.hot.accept()
}

console.log('value of something', something)

// devServer.js

const Path = require('path')
const PundleDev = require('pundle-dev')

const server = new PundleDev({
  server: {
    hmr: true,
    port: 8765,
    hmrPath: '/bundle_hmr',
    bundlePath: '/bundle.js',
    sourceRoot: Path.join(__dirname, 'public'),
    sourceMapPath: '/bundle.js.map',
    error(error) {
      console.error(error)
    }
  },
  pundle: {
    entry: [require.resolve('./index.ts')],
    pathType: 'filePath',
    rootDirectory: __dirname,
    replaceVariables: {
      'process.env.NODE_ENV': 'development',
    }
  },
  watcher: { },
  generator: {
    wrapper: 'hmr',
    sourceMap: true
  }
})

server.pundle.loadPlugins([
  ['pundle-typescript']
]).then(() => {
  server.pundle.loadLoaders([
    { extensions: ['.ts'], loader: require('pundle/lib/loaders/javascript').default },
  ])
  return server.activate()
}).then(function() {
  console.log('Dev server is listening')
}).catch(console.error)
```

**Comment by steelbrain** [comment]
I've actually already published it but under [`typescript-pundle`](https://www.npmjs.com/package/typescript-pundle) instead of `pundle-typescript`
