### ISSUE TITLE
Decide on name for config file

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/pundle#85]
Follow up to #75

**Comment by appsforartists** [comment]
tl:dr:

- `Pundleconfig.js` is wonky - initial cap + no separation makes it stick out
- `pundle.config.js` proposed as alternative.  @steelbrain thinks it may be too long

Other common tools use:
- `webpack.config.js`
- `tsconfig.json`

**Comment by steelbrain** [comment]
What do you think about `.pundle.js`?

**Comment by appsforartists** [comment]
I don't hate it, though I still wonder if this is confusing: 

```js
import Pundle from "pundle";
import pundleSettings from "./.pundle";
```

**Comment by steelbrain** [comment]
I don't know of any use case where the end user will have to require the pundle config. It'll be used and found automatically by Pundle itself

**Comment by appsforartists** [comment]
So if I want to configure a dev server, for instance, I don't also have to pass in the common config into the PundleDev constructor?

**Comment by steelbrain** [comment]
If you want to configure a dev server, you can set these types in the Pundle config file

```js
{
  output: {
    bundlePath?: string,
    sourceMap?: boolean,
    sourceMapPath?: string,
  },
  server: {
    redirectNotFoundToIndex?: boolean
  },
}
```

**Comment by steelbrain** [comment]
If you want to run the dev server, just set it's options in Pundle config file and launch pundle with `-d`. The dev server doesn't have a lot of config btw, the ones it has are documented above

**Comment by appsforartists** [comment]
Interesting: so one config works for both the dev server and production bundling, with the expectation that `package.json` looks something like:

```json
"scripts": {
  "start": "$( yarn bin )/pundle -d",
  "build": "$( yarn bin )/pundle",
```

**Comment by steelbrain** [comment]
Had a private discord conversation with @appsforartists, We both agree on `.pundle.js`

**Comment by steelbrain** [comment]
It has been set to `.pundle.js` in v2 branch, and will be released with v2Alpha4
