### ISSUE TITLE
pundle-cli can't find its entry

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#86]
`${ project root }` replaces with my actual path for privacy

```
> yarn add pundle-cli@2.0.0-alpha1

> $(yarn bin)/pundle
Error Cannot find module '${ project root }/src/mount.tsx'

> cat ${ project root }/src/mount.tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';

import Main from './components/Main';

ReactDOM.render(
  <Main />,
  document.getElementById('root')
);

if (module.hot) {
  module.hot.accept()
}

> cat Pundleconfig.js 
module.exports = {
  entry: [require.resolve('./src/mount.tsx')],
  pathType: 'filePath',
  rootDirectory: __dirname,
  replaceVariables: {
    'process.env.NODE_ENV': 'development',
  },
}
```

**Comment by appsforartists** [comment]
Adding typescript didn't help:

```
module.exports = {
  entry: [require.resolve('./src/mount.tsx')],
  pathType: 'filePath',
  rootDirectory: __dirname,
  replaceVariables: {
    'process.env.NODE_ENV': 'development',
  },

  components: [
    [
      require.resolve('pundle-transformer-typescript'),
      {
        config: {
          compilerOptions: {
            jsx: 'react',
            strictNullChecks: true,
          }
        },
        include: ['*.ts', '*.tsx'],
      }
    ],
  ]
}
```

**Comment by steelbrain** [comment]
That's because the Pundle package is bare bones by default. To make it recognize this extension or any extension, we have to add the resolver component (you are also gonna need others like generators etc). So I would recommend you use the `pundle-preset-default` package like

```
module.exports = {
  presets: [
    [require.resolve('pundle-preset-default'), {
      resolver: { extensions: ['', '.js', '.tsx', '.ts', '.json'] }
    }]
  ]
}
```

I'll push an update soon where these extensions will be automatically derived from all registered loaders so you just have to give it the path to the preset

**Comment by steelbrain** [comment]
@appsforartists Are you on any slack? I don't usually feel comfortable using Github issues for PM but the Alpha1 had a bug in JS loader that caused a lot of apps to crash. I've fixed it in the branch so just a heads up

**Comment by appsforartists** [comment]
Nah - we use Discord because Slack kicked off Reactiflux, so we avoid using it for OSS projects.  I could always sign up, but I can't promise I'll remember to use it.

**Comment by steelbrain** [comment]
@appsforartists I'm `steel-brain#5289` on discord

**Comment by steelbrain** [comment]
Pundle@2 second alpha automatically determines the extensions based on the `loader` components. Thinking about adding support for `transformer` components too

**Comment by steelbrain** [comment]
Closing as this is no longer relevant
