### ISSUE TITLE
pundle-dev: default to index.html

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#89]
Firebase hosting has a neat feature where you can direct all missed URLs to a single file (index.html).  They specifically advertise it for single-page apps (where the routing is handled by something like React Router).

Can I configure Pundle do this too?  I'd love to have my local and hosted apps behave as identically as possibly.  It's also nice not to get a 404 if you reload on a client-side route.

**Comment by steelbrain** [comment]
I need this for Motion too. Thanks for opening this!

**Comment by steelbrain** [comment]
This has been implemented and will land as part of Alpha 3 of v2
