### ISSUE TITLE
config.entry should be an Array or string error if TypeScript not installed

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#91]
I think the config.entry error is too greedy in Pundle 2.  I get this error if the TypeScript Transformer can't find TypeScript:

"config.entry should be an Array or string"

**Comment by steelbrain** [comment]
That error message for when Typescript is not found is certainly not the expected behavior. Thank you for the request

**Comment by steelbrain** [comment]
Thank you for the report 👍 
This has been fixed in https://github.com/motion/pundle/commit/3d0b39f15cef70a27c6be8c4165b3670a147011c
