### ISSUE TITLE
Release typescript-pundle@1.1.12

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#95]
Hey @steelbrain, can you please push a new build to NPM with #93?

Thanks!

**Comment by steelbrain** [comment]
Yes, I am working on a CLI for Pundle that's almost done, I'll release it with the new CLI :) It should be sometime today

**Comment by steelbrain** [comment]
Wait no, I thought you meant the Pundle beta. I've published `1.1.12` that includes the PR referenced

**Comment by appsforartists** [comment]
thanks!
