### ISSUE TITLE
config.server.devDirectory isn't taking effect

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#97]
Using pundle@2.0.0-beta2

`pundle --dev --dev-directory site` serves ./site/index.html

but `pundle --dev` with

```javascript
  server: {
    devDirectory: path.join(__dirname, 'site'),
```
doesn't:

```
Error: ENOENT: no such file or directory, stat '~/Projects/material-motion-js/packages/demos-react/index.html'
```

See my config [here](http://codereview.cc/D2413?vs=9113&id=9114&whitespace=ignore-most#toc)

**Comment by steelbrain** [comment]
Fixed in https://github.com/motion/pundle/pull/75/commits/3bc3014a00039beca00bbaa78cd22ca1e9750996 and will be part of beta3

Thanks again for your continued testing 👍
