### ISSUE TITLE
Pundle HMR presumes it's serving the HTML

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#98]
I'm experimenting with using Pundle to serve a Chrome Extension background page (to help get around CORS issues).  Pundle HMR tries to open a WebSocket at `location.host`, which is a random hash in a Chrome Extension.  Is there a way to tell it to use `localhost:8080`?

```
    hmrPath: 'http://localhost:8080/dist/bundle_hmr',
```

leads to

```
bundle.js:4 WebSocket connection to 'ws://nogdfjgccijimfadaajlhlaaelmjgmnohttp//localhost:8080/dist/bundle_hmr'
```

**Comment by steelbrain** [comment]
I overlooked this scenario because I personally use an nginx proxy that combines multiple sources including the pundle server so it's all available in the same port.

I'll add an option for it, thank you for reporting 👍

**Comment by steelbrain** [comment]
This has been fixed and will be part of the next beta (beta3)

**Comment by appsforartists** [comment]
Yay! Thanks!
